### ISSUE TITLE
No ooo-response with renamed person from LDAP sync

### ISSUE THREAD

**Issue by TThelpdesk** [graywolf336/RocketChatApps#18]
Hello team,

atm we have an error with ooo responder for one colleague. This is the log from one try to get the message. The responder was set by myself, so everything is ok. We have tried it with other users, there are no errors.

The user with the error got renamed by us because she married. The users are synced by LDAP connection. In my case, the chat with the user is still with the old name. One of my colleagues deleted the chat and created it new, then the chat has her new name and with this one the message occurs as it should.

This is the error. Can you check if it is possible to get it worked with both? I don't think anyone deletes its chat with her when she got renamed.

```
September 6, 2021 11:55: "executePostMessageSent" (6ms)
Instance: fgadEQqEKMYfy5QAY
debug: 2021-09-06T09:55:33.039Z Anrufer: anonymous OR constructor
[
  "executePostMessageSent is being called..."
]
error: 2021-09-06T09:55:33.045Z Anrufer: anonymous OR constructor
[
  "{\"stack\":\"TypeError: Cannot read property 'id' of undefined\\n    at OutOfOfficeApp.executePostMessageSent (evalmachine.<anonymous>:19:120)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\",\"message\":\"Cannot read property 'id' of undefined\"}"
]
debug: 2021-09-06T09:55:33.045Z Anrufer: anonymous OR constructor
[
  "'executePostMessageSent' was unsuccessful."
]
```

Thanks for your help

**Comment by ceriath** [comment]
Hi, i just opened a pull request (#20) for this. I also create a release, until the PR is merged and published. https://github.com/ceriath/RocketChatApps/releases/tag/ooo-1.3.0

**Comment by graywolf336** [comment]
Closing thanks to @ceriath for #20 🎉
