### ISSUE TITLE
out-of-office does not work anymore since 4.0

### ISSUE THREAD

**Issue by himpierre** [graywolf336/RocketChatApps#19]
Hello Graywolf336.

Since 4.x the out-of-office app is not working anymore. After enabling it there is no notification if someone sends a message to the out-of-office enabled user. There is nothing in the logs. 

Setup: Rocketchat 4.1.2, Kubernetes, 4 Rocketchat Nodejs Pods. 

Is there something I can do, to help finding the underlaying issue here?

cheers, t.

**Comment by kaiiiiiiiii** [comment]
Can confirm, still able to set o-o-o status, but no messages are sent.

**Comment by ceriath** [comment]
Hi, i just opened a pull request (#20) for this. I also create a release, until the PR is merged and published. https://github.com/ceriath/RocketChatApps/releases/tag/ooo-1.3.0
