### ISSUE TITLE
Out-Of-Office Responder not installable on Rocketchat 6.1.2

### ISSUE THREAD

**Issue by himpierre** [graywolf336/RocketChatApps#42]
Hello @graywolf336 

Out-Of-Office Responder is not installable with Rocketchat 6.1.2. When I hit the install button in the marketplace it jumps right back to the previous view suggesting to install the app. Any hopes for getting this running with 6.1.2?

cheers, t.

**Comment by graywolf336** [comment]
Are you installing it from Marketplace or are you installing it by uploading the app?

**Comment by graywolf336** [comment]
@himpierre please open an issue at https://github.com/RocketChat/Rocket.Chat and let them know how to replicate your bug. You can try this one: https://github.com/ceriath/RocketChatApps/releases/tag/1.2.1

**Comment by himpierre** [comment]
Well, the app was already installed and was hiding in a disabled state under "private apps". did not look there. I just needed to enable it. Everything works now. Sorry for the noise.

cherrs, t.

Am 19. April 2023 21:54:32 MESZ schrieb Bradley Hilton ***@***.***>:
>@himpierre please open an issue at https://github.com/RocketChat/Rocket.Chat and let them know how to replicate your bug.
>
>You can try this one zip: https://github.com/ceriath/RocketChatApps/releases/tag/1.2.1
>

**Comment by graywolf336** [comment]
Ah, good to know. Thank you for the update! Still, sounds like there is a bug in rocket.chat. You shouldn't of had to search and find that, they should have made it abundantly clear.
