### ISSUE TITLE
Get a reminder that your status is set out-of-office

### ISSUE THREAD

**Issue by nopynoop** [graywolf336/RocketChatApps#5]
Thank you for developing this useful app.

However, I sometimes forget to put my status back to normal and people I talk to get flooded that I am out of office. It would be nice to get a reminder that my status is set out-of-office when I reply to messages.

**Comment by graywolf336** [comment]
Fantastic idea!

**Comment by mikemkm** [comment]
Totally agree! Great add-on! :)
Any chance that this OOO reminder proposed by @nopynoop will be implemented someday?

**Comment by graywolf336** [comment]
Someday, absolutely!

**Comment by graywolf336** [comment]
Just published a version with this in there. :) I will improve it all in a few weeks
