### ISSUE TITLE
Is it the wrong link? Description missing 

### ISSUE THREAD

**Issue by 42robotsCS** [graywolf336/RocketChatApps#7]
Hi there !

Just wondered about the readme and the repo - there is no info about how the out of office reminder supposed to work, however its available in the marketplace - 
Would be great to have a clear documentation and App instruction, otherwise it lacks good quality and should not appear inside the marketpleace.
No offense intended here, but i guess this should be a standard for the marketplace apps (even if they are still beta).

Best,
Chris

**Comment by graywolf336** [comment]
Feel free to submit a pull request as an example of what you have in mind! :)

**Comment by Silimilikim** [comment]
I guess he means that there's no explanation about how to use the app. It's nowhere to find. I just found out by chance that you have to type /out-of-office in the chat then in or out then the message you want to send to people. I think you should write it down it in your readme file so everyone, even beginners, can use your app.

**Comment by graywolf336** [comment]
Makes perfect sense, thanks for helping provide clarification.

**Comment by graywolf336** [comment]
https://github.com/graywolf336/RocketChatApps/blob/master/out-of-office/README.md
