### ISSUE TITLE
Out of office responder generates error messages in rocketchat log

### ISSUE THREAD

**Issue by sketch242** [graywolf336/RocketChatApps#9]
This is on the out of office responder installed via the marketplace, on RC 0.74.3, Apps engine version 1.4.0.

I seem to get a constant stream of messages in the rocketchat log, even when set to errors only.  It appears to log this for every message received by a user:

```
Jul 10 11:45:16 vdrc01 RocketChat[3394]: Checking: checkPostMessageSent
Jul 10 11:45:16 vdrc01 RocketChat[3394]: Checking: executePostMessageSent
Jul 10 11:45:16 vdrc01 RocketChat[3394]: The App 09a2b0d8-94d0-433d-a53e-3961a3bb0205 is getting the username: "myuser"
Jul 10 11:45:16 vdrc01 RocketChat[3394]: The App 09a2b0d8-94d0-433d-a53e-3961a3bb0205 is searching for records that are associated with the following: [ RocketChatAssociationRecord { model: 'user', id: 'e8f2cP37zGZ4xap55' } ]
```

**Comment by graywolf336** [comment]
You will need to update your Rocket.Chat version. This is actually logging done by Rocket.Chat itself and not the App. This was fixed in one of the latest updates, so you will need to update.

**Comment by sennewood** [comment]
We use Rocket.Chat 3.4.2 and set the loglevel to "0 - errors only". Since we use the app/plugin the livelog is quasi unusable.
Isn't there a way for the app/plugin to tell RC a loglevel?

**Comment by sennewood** [comment]
Still a problem with 3.10.0

**Comment by graywolf336** [comment]
@sennewood this is because you have development mode enabled inside your Rocket.Chat instance:

https://github.com/RocketChat/Rocket.Chat/blob/2de76ab2aa9a6f03796f57494d78e7b9590379cf/app/apps/server/orchestrator.js#L116-L121

https://github.com/RocketChat/Rocket.Chat/blob/2de76ab2aa9a6f03796f57494d78e7b9590379cf/app/apps/server/bridges/users.js#L19
